/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#565e74",
        "on-secondary-container": "#fefcff",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-container": "#009668",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container": "#e5eeff",
        "outline": "#76777d",
        "primary-container": "#131b2e",
        "inverse-surface": "#213145",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "border-subtle": "#E2E8F0",
        "tertiary": "#000000",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9ff",
        "surface-base": "#FFFFFF",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "surface-muted": "#F8FAFC",
        "on-secondary-fixed-variant": "#004395",
        "secondary-fixed": "#d8e2ff",
        "surface-dim": "#cbdbf5",
        "primary": "#000000",
        "on-primary-fixed": "#131b2e",
        "on-error": "#ffffff",
        "secondary": "#0058be",
        "on-primary-container": "#7c839b",
        "outline-variant": "#c6c6cd",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#2170e4",
        "background": "#f8f9ff",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#45464d",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-highest": "#d3e4fe",
        "accent-warm": "#F59E0B",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#002113",
        "on-background": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed": "#dae2fd",
        "tertiary-container": "#002113",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "stack-lg": "24px",
        "stack-xl": "48px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "base": "4px",
        "gutter": "24px",
        "max-width": "1280px",
        "stack-xs": "4px",
        "stack-sm": "8px"
      },
      "fontFamily": {
        "headline-xl": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "button": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"]
      },
      "fontSize": {
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "button": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
